# See https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_generator#buildyaml-configuration
# Configures `build_runner` to only run `riverpod_generator` on the `lib` folder.
# This prevents issues with test files and improves build performance.
targets:
  $default:
    builders:
      riverpod_generator|riverpod_generator:
        enabled: true
        generate_for:
          # Only include files in the lib directory
          - lib/**
      # Explicitly configure mockito builder again
      mockito|mockBuilder:
        enabled: true
        generate_for:
          - test/mocks/core_mocks.dart # Target the specific file
        # options: # Default options, can be customized if needed
          # provider_name_suffix: 'Provider'
          # provider_name_prefix: '_'
          # etc.

# Previous attempt (excluding test/** from riverpod seemed insufficient)
# targets:
#   $default:
#     builders:
#       riverpod_generator|riverpod_generator:
#         enabled: true
#         generate_for:
#           # Only include files in the lib directory
#           - lib/**
#           # Explicitly exclude test directories (This part might not work as expected)
#           # - test/** 
#           # - integration_test/**
#         options:
#           # Default options, can be customized if needed
#           # provider_name_suffix: 'Provider'
#           # provider_name_prefix: '_'
#           # etc. 